[workspace]
members = [
    "AoC_12_1",
    "AoC_12_2",
    "AoC_12_3",
    "AoC_12_4",
    "AoC_12_5",
    "AoC_12_6",
    "AoC_12_7",
    "AoC_12_8",
    "AoC_12_9",
    "AoC_12_10",
    "AoC_12_11",
    "AoC_12_12",
    "AoC_12_13",
    "AoC_12_14",
    "AoC_12_15",
    "AoC_12_16",
    "AoC_12_17",
]